workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
