name: mohasib_rawa
description: Full-featured Flutter accounting app (v4) — Isar, auth, permissions, invoices, Google Drive backup, Excel export, Bluetooth printing.
publish_to: 'none'
version: 0.3.0
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: ^4.0.0
  isar_flutter_libs: any
  path_provider: ^2.0.15
  intl: ^0.18.0
  printing: ^5.10.0
  share_plus: ^6.3.0
  shared_preferences: ^2.1.1
  flutter_blue_plus: ^1.3.0
  uuid: ^4.1.0
  provider: ^6.0.5
  flutter_barcode_scanner: ^2.0.0
  flutter_slidable: ^2.0.0
  google_sign_in: ^6.0.0
  googleapis: ^9.0.0
  excel: ^2.0.0
  google_fonts: ^5.0.0
  workmanager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  isar_generator: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/